# Generated by Django 4.1.1 on 2022-10-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_familiar_delete_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimiento',
            new_name='fecha_creacion',
        ),
    ]
